# -*- coding: utf-8 -*-
"""20N3050 AIプログラミング最終課題

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bp-JQ_R3lBOeMpQjOw5LXLgqxnyccx97
"""

import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

mnist_x, mnist_y = fetch_openml('mnist_784', version=1, data_home="sklearn_MNIST_data", return_X_y=True)
list_mnist_x = np.array(mnist_x)
list_mnist_y = np.array(mnist_y)

data_train, data_test, target_train, target_test = train_test_split(list_mnist_x, list_mnist_y, random_state=43)

data_train /= 255
data_test /= 255

clf = MLPClassifier(hidden_layer_sizes=(100,), verbose=True, max_iter=100, random_state=43, alpha=0.01)

clf.fit(data_train, target_train)

predict = clf.predict(data_test)

# 正解率
print(clf.score(data_test, target_test))